# Site settings
title: Alena Rottensteiner
description: Website under construction
baseurl: ""          # If your site is at username.github.io, keep this blank. If in a subfolder, set appropriately.
url: "https://rottenstea.github.io"    # change to your own site URL

# Theme
theme: jekyll-theme-minimal        # you can choose a different Jekyll theme if you like

# Navigation / pages
# We'll define a navigation menu for use in layouts
nav:
  - title: Home
    url: "/"
  - title: Contact
    url: "/contact/"

# Markdown / plugins config
markdown: kramdown
kramdown:
  input: GFM

