# Site settings
title: Alena Rottensteiner
description: Website under construction
baseurl: ""          # leave blank for username.github.io root
url: "https://rottenstea.github.io"


theme: jekyll-theme-minimal

# Navigation / pages
nav:
  - title: Home
    url: "/"
  - title: About
    url: "/about/"
  - title: CV
    url: "/cv/"
  - title: Contact
    url: "/contact/"

# Markdown / plugins config
markdown: kramdown
kramdown:
  input: GFM
